# -*- coding: utf-8 -*-
"""Juego de Carros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OdqdaNo-9e95UY2awlaNdSLtakbd1VgT
"""

import random
import os
import time

os.system("cls")
class Juego:
  def __init__(self,ID):    
    self.ID = ID     
    print("Juego", ID ,"creado")  

class Carro:
  def __init__(self,piloto,num):
    self.piloto=piloto
    self.posicion = 0
  def __str__(self):
    return self.piloto
  def avanzar(self):
    self.posicion += random.randint(1,6)*100

class Pista:
  def __init__(self,carriles, dist, guia):
    self.carriles = carriles
    self.dist = dist
    self.guia = guia
    self.pista= []
    for i in range(carriles):
      self.pista.append([guia]*dist)
    print('Pista creada, con', self.carriles, 'carriles') 

  def ubicar_carro(self,carro,carril,posicion):
    self.pista[carril][posicion] = carro
  
  def mostrar(self):
    print("  SALIDA  "+ ("-"*((self.dist)-4))+ "|| META")
    for i in range(self.carriles):
      print(" ", end=" ")
      for j in range(self.dist):
        print(self.pista[i][j],end="")
      print()

class Jugador:
  def __init__(self, nombre):
    self.nombre = nombre
  
class Conductor(Jugador):  
  def new(self,Ncarril,Ncarro):          
    self.Ncarril = Ncarril
    self.Ncarro = Ncarro

os.system("cls")

archivo = open("podio.txt",'w')
archivo.close
print("  CARRERAS DE CARROS  ")
juego = Juego(random.randrange(1,1000))
Jugadores = []
#nombres = ["maria","juan", "carla", "mateo"]
carros= []
print("Escribe a continuación los nombres de los jugadores: ")
nom = input("Nombre del jugador (n para no añadir mas jugadores): ")
while nom != 'n': 
  Jugadores.append(nom)  
  nom = input("Nombre del jugador (n para no añadir mas jugadores): ")

distkm = int(input("Kilometros de la pista: "))*1000
pista = Pista(len(Jugadores),distkm,"-")

for i in range(pista.carriles):
  num = random.randint(1,100)
  carro = Carro(Jugadores[i],num)
  carros.append(carro)

for i in range(pista.carriles):
  pista.ubicar_carro(carros[i],i,carros[i].posicion) 

os.system("cls")
pista.mostrar()

print()
while True:

  os.system("cls")
  podio = []  
  for carro in carros:
    if carro.posicion > pista.dist-3:
      podio.append(carro)
  if len(podio) > 0:
    break
  
  for i in range(pista.carriles):
    pista.ubicar_carro(pista.guia, i,carros[i].posicion)
    carros[i].avanzar()
    pista.ubicar_carro(carros[i],i,carros[i].posicion)
  
  pista.mostrar()
  time.sleep(1)

pista.mostrar()

archivo = open("podio.txt",'w')
print("Podio")
for carro in podio:
  print("Primer puesto", podio[0])
  #print("Segundo puesto",podio[1])
  #print("Tercer puesto", podio[2])
archivo.write(podio)
archivo.close
print()

print(podio[0])